grails-app/domain/com/example/Permission.groovy
package com.example

class Permission {

	String moduleName // Modules name e.g Role, Customer etc.
	String permissionName // Add, Delete etc.
	String permissionString // "role:create,role:dashboard,role:save,role:index" , commad sep string
	//Permission parentModuleName // Role, Customer 
	String description
	Date dateCreated
	Date lastUpdated
	
    static constraints = {
		moduleName nullable : false, blank : false
		permissionName nullable : false, blank : false
		//parentModuleName nullable : true, blank : true
		description nullable : true, blank : true
    }
}

grails-app/domain/com/example/Role.groovy
package com.example

class Role {
    String name
	List previledges
	List permissions
    static hasMany = [ users: User, permissions: String, previledges : Permission]
    static belongsTo = User

    static constraints = {
        name(nullable: false, blank: false, unique: true)
		previledges (nullable: true, blank: true)
    }
}

grails-app/domain/com/example/User.groovy
package com.example

class User {
    String username
    String passwordHash
    
    static hasMany = [ roles: Role, permissions: String ]

    static constraints = {
        username(nullable: false, blank: false, unique: true)
    }
}

grails-app/controllers/com/example/AuthController.groovy
package com.example

import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.web.util.SavedRequest
import org.apache.shiro.web.util.WebUtils

class AuthController {
    def shiroSecurityManager

    def index = { redirect(action: "login", params: params) }

    def login = {
        return [ username: params.username, rememberMe: (params.rememberMe != null), targetUri: params.targetUri ]
    }

    def signIn = {
        def authToken = new UsernamePasswordToken(params.username, params.password as String)

        // Support for "remember me"
        if (params.rememberMe) {
            authToken.rememberMe = true
        }
        
        // If a controller redirected to this page, redirect back
        // to it. Otherwise redirect to the root URI.
        def targetUri = params.targetUri ?: "/"
        
        // Handle requests saved by Shiro filters.
        SavedRequest savedRequest = WebUtils.getSavedRequest(request)
        if (savedRequest) {
            targetUri = savedRequest.requestURI - request.contextPath
            if (savedRequest.queryString) targetUri = targetUri + '?' + savedRequest.queryString
        }
        
        try{
            // Perform the actual login. An AuthenticationException
            // will be thrown if the username is unrecognised or the
            // password is incorrect.
            SecurityUtils.subject.login(authToken)

            log.info "Redirecting to '${targetUri}'."
            redirect(uri: targetUri)
        }
        catch (AuthenticationException ex){
            // Authentication failed, so display the appropriate message
            // on the login page.
            log.info "Authentication failure for user '${params.username}'."
            flash.message = message(code: "login.failed")

            // Keep the username and "remember me" setting so that the
            // user doesn't have to enter them again.
            def m = [ username: params.username ]
            if (params.rememberMe) {
                m["rememberMe"] = true
            }

            // Remember the target URI too.
            if (params.targetUri) {
                m["targetUri"] = params.targetUri
            }

            // Now redirect back to the login page.
            redirect(action: "login", params: m)
        }
    }

    def signOut = {
        // Log the user out of the application.
        SecurityUtils.subject?.logout()
        webRequest.getCurrentRequest().session = null

        // For now, redirect back to the home page.
        redirect(uri: "/")
    }

    def unauthorized = {
        render "You do not have permission to access this page."
    }
}

grails-app/controllers/com/example/OneController.groovy
package com.example

class OneController {

    def index() { }
	
	def create() {}
	
	def save(){}
	
	def edit(){}
	
	def delete(){}
	
	def update(){}
}

grails-app/controllers/com/example/RoleController.groovy
package com.example

class RoleController {

    def index() {
		def permissionList = Permission.list()
		permissionList = permissionList.groupBy{it.moduleName}
		
		def roleList = Role.list()
		println "List :" + permissionList
		[permissionList : permissionList, roleList : roleList]	
	}
	
	def save(){
		println "Role Params :" + params
		redirect(action : 'index')
	}
	
	def edit(){
		def roleInstance = Role.read(params?.id)
		def assignedPermissionList = roleInstance?.previledges
		
		def permissionList = Permission.list()
		permissionList = permissionList.groupBy{it.moduleName}
		
		[assignedPermissionList : assignedPermissionList, roleInstance : roleInstance, permissionList : permissionList]
	}
	
	def update(){
		println "Test : " + params?.rolePermission
		def rolePermissionList = params?.rolePermission 
		def roleInstance = Role.read(params?.id)
		
		roleInstance?.previledges.clear()
		roleInstance?.permissions.clear()
		
		rolePermissionList.each{
			def permissionInstance = Permission.read(it as Long)
			println "permissionInstance :" + permissionInstance
			permissionInstance.permissionString.split(",").each{ roleInstance.addToPermissions(it)}
			roleInstance.addToPreviledges(permissionInstance)
		}
		
		roleInstance.save(flush:true)
		
		redirect(action : 'edit', id : params?.id)
	}
}

grails-app/controllers/com/example/TwoController.groovy
package com.example

class TwoController {

    def index() { }
	
	def create() {}
	
	def save(){}
	
	def edit(){}
	
	def delete(){}
	
	def update(){}
}

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'multi-select.css')}" type="text/css">
		
		 <script src="${resource(dir: 'js', file: 'jquery-1.10.2.js')}"></script>
		<g:layoutHead/>
		<g:javascript library="application"/>		
		<r:layoutResources />
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><img src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Grails"/></a></div>
		<shiro:isLoggedIn>
		<g:link action="signOut" controller="auth"> Signout </g:link><br>
		</shiro:isLoggedIn>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<r:layoutResources />
	</body>
</html>

grails-app/views/one/index.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main"/>
		<title>Welcome to Grails</title>
		<style type="text/css" media="screen">
			#status {
				background-color: #eee;
				border: .2em solid #fff;
				margin: 2em 2em 1em;
				padding: 1em;
				width: 12em;
				float: left;
				-moz-box-shadow: 0px 0px 1.25em #ccc;
				-webkit-box-shadow: 0px 0px 1.25em #ccc;
				box-shadow: 0px 0px 1.25em #ccc;
				-moz-border-radius: 0.6em;
				-webkit-border-radius: 0.6em;
				border-radius: 0.6em;
			}

			.ie6 #status {
				display: inline; /* float double margin fix http://www.positioniseverything.net/explorer/doubled-margin.html */
			}

			#status ul {
				font-size: 0.9em;
				list-style-type: none;
				margin-bottom: 0.6em;
				padding: 0;
			}

			#status li {
				line-height: 1.3;
			}

			#status h1 {
				text-transform: uppercase;
				font-size: 1.1em;
				margin: 0 0 0.3em;
			}

			#page-body {
				margin: 2em 1em 1.25em 18em;
			}

			h2 {
				margin-top: 1em;
				margin-bottom: 0.3em;
				font-size: 1em;
			}

			p {
				line-height: 1.5;
				margin: 0.25em 0;
			}

			#controller-list ul {
				list-style-position: inside;
			}

			#controller-list li {
				line-height: 1.3;
				list-style-position: inside;
				margin: 0.25em 0;
			}

			@media screen and (max-width: 480px) {
				#status {
					display: none;
				}

				#page-body {
					margin: 0 1em 1em;
				}

				#page-body h1 {
					margin-top: 0;
				}
			}
		</style>
	</head>
	<body>
	
		<shiro:hasPermission permission="one:index">
			Index
			<br>
		</shiro:hasPermission>
		<shiro:hasPermission permission="one:add">	
			Add
			<br>
		</shiro:hasPermission>
		<shiro:hasPermission permission="one:save">	
			Save
			<br>
		</shiro:hasPermission>
		<shiro:hasPermission permission="one:edit">		
			Edit
			<br>
		</shiro:hasPermission>	
		<shiro:hasPermission permission="one:update">	
			Update
			<br>
		</shiro:hasPermission>
		<shiro:hasPermission permission="one:delete">		
			Delete
		</shiro:hasPermission>	
			
	</body>
</html>

grails-app/views/role/edit.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main"/>
		<title>Welcome to Grails</title>
		<style type="text/css" media="screen">
			#status {
				background-color: #eee;
				border: .2em solid #fff;
				margin: 2em 2em 1em;
				padding: 1em;
				width: 12em;
				float: left;
				-moz-box-shadow: 0px 0px 1.25em #ccc;
				-webkit-box-shadow: 0px 0px 1.25em #ccc;
				box-shadow: 0px 0px 1.25em #ccc;
				-moz-border-radius: 0.6em;
				-webkit-border-radius: 0.6em;
				border-radius: 0.6em;
			}

			.ie6 #status {
				display: inline; /* float double margin fix http://www.positioniseverything.net/explorer/doubled-margin.html */
			}

			#status ul {
				font-size: 0.9em;
				list-style-type: none;
				margin-bottom: 0.6em;
				padding: 0;
			}

			#status li {
				line-height: 1.3;
			}

			#status h1 {
				text-transform: uppercase;
				font-size: 1.1em;
				margin: 0 0 0.3em;
			}

			#page-body {
				margin: 2em 1em 1.25em 18em;
			}

			h2 {
				margin-top: 1em;
				margin-bottom: 0.3em;
				font-size: 1em;
			}

			p {
				line-height: 1.5;
				margin: 0.25em 0;
			}

			#controller-list ul {
				list-style-position: inside;
			}

			#controller-list li {
				line-height: 1.3;
				list-style-position: inside;
				margin: 0.25em 0;
			}

			@media screen and (max-width: 480px) {
				#status {
					display: none;
				}

				#page-body {
					margin: 0 1em 1em;
				}

				#page-body h1 {
					margin-top: 0;
				}
			}
		</style>
		<script>
		 $( document ).ready(function() {
			 $('#optgroup').multiSelect({ selectableOptgroup: true });
		 });
		</script>
	</head>
	<body>
			<g:form name="roleUpdate" action="update">
			<g:hiddenField name="id" value="${roleInstance?.id}"/>
			<select id='optgroup' multiple='multiple' name="rolePermission">
			 <g:each in="${permissionList}" status="i" var="permissionInstnace">
					  <optgroup label='${permissionInstnace.key}'>
						  <g:each in="${permissionInstnace.value}" var="permissionValueInstance">
						  			<g:if test="${assignedPermissionList.contains(permissionValueInstance)}">
						    			<option value='${permissionValueInstance?.id}' selected="selected">${permissionValueInstance?.permissionName}</option>
						    		</g:if>
						    		<g:else>
						    			<option value='${permissionValueInstance?.id}' >${permissionValueInstance?.permissionName}</option>
						    		</g:else>
						  </g:each>
					  </optgroup>
				
				 	</g:each> 
				
				</select>
				
				<br>
				<input type="submit" value="Save" />
			</g:form>	
			
			<br>
		    <script src="${resource(dir: 'js', file: 'jquery.multi-select.js')}"></script>
	</body>
</html>

grails-app/views/role/index.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main"/>
		<title>Welcome to Grails</title>
		<style type="text/css" media="screen">
			#status {
				background-color: #eee;
				border: .2em solid #fff;
				margin: 2em 2em 1em;
				padding: 1em;
				width: 12em;
				float: left;
				-moz-box-shadow: 0px 0px 1.25em #ccc;
				-webkit-box-shadow: 0px 0px 1.25em #ccc;
				box-shadow: 0px 0px 1.25em #ccc;
				-moz-border-radius: 0.6em;
				-webkit-border-radius: 0.6em;
				border-radius: 0.6em;
			}

			.ie6 #status {
				display: inline; /* float double margin fix http://www.positioniseverything.net/explorer/doubled-margin.html */
			}

			#status ul {
				font-size: 0.9em;
				list-style-type: none;
				margin-bottom: 0.6em;
				padding: 0;
			}

			#status li {
				line-height: 1.3;
			}

			#status h1 {
				text-transform: uppercase;
				font-size: 1.1em;
				margin: 0 0 0.3em;
			}

			#page-body {
				margin: 2em 1em 1.25em 18em;
			}

			h2 {
				margin-top: 1em;
				margin-bottom: 0.3em;
				font-size: 1em;
			}

			p {
				line-height: 1.5;
				margin: 0.25em 0;
			}

			#controller-list ul {
				list-style-position: inside;
			}

			#controller-list li {
				line-height: 1.3;
				list-style-position: inside;
				margin: 0.25em 0;
			}

			@media screen and (max-width: 480px) {
				#status {
					display: none;
				}

				#page-body {
					margin: 0 1em 1em;
				}

				#page-body h1 {
					margin-top: 0;
				}
			}
		</style>
		<script>
		 $( document ).ready(function() {
			 $('#optgroup').multiSelect({ selectableOptgroup: true });
		 });
		</script>
	</head>
	<body>
			<g:form name="roleSave" action="save">
			<select id='optgroup' multiple='multiple' name="rolePermission">
				<g:each in="${permissionList}" status="i" var="permissionInstnace">
				  <optgroup label='${permissionInstnace.key}'>
					  <g:each in="${permissionInstnace.value}" var="permissionValueInstance">
					    <option value='${permissionValueInstance?.id}'>${permissionValueInstance?.permissionName}</option>
					  </g:each>
				  </optgroup>
				 </g:each> 
				</select>
				<br>
				<input type="submit" value="Save" />
			</g:form>	
			
			<br>
			<g:each in="${roleList}" status="i" var="roleInstance">
				<table>
					<tr>
						<td width="30%">${roleInstance?.name}</td>
						<td><g:link action="edit" id="${roleInstance?.id}">Edit</g:link> </td>
					</tr>
				</table>
			</g:each>
		    <script src="${resource(dir: 'js', file: 'jquery.multi-select.js')}"></script>
	</body>
</html>

grails-app/views/two/index.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main"/>
		<title>Welcome to Grails</title>
		<style type="text/css" media="screen">
			#status {
				background-color: #eee;
				border: .2em solid #fff;
				margin: 2em 2em 1em;
				padding: 1em;
				width: 12em;
				float: left;
				-moz-box-shadow: 0px 0px 1.25em #ccc;
				-webkit-box-shadow: 0px 0px 1.25em #ccc;
				box-shadow: 0px 0px 1.25em #ccc;
				-moz-border-radius: 0.6em;
				-webkit-border-radius: 0.6em;
				border-radius: 0.6em;
			}

			.ie6 #status {
				display: inline; /* float double margin fix http://www.positioniseverything.net/explorer/doubled-margin.html */
			}

			#status ul {
				font-size: 0.9em;
				list-style-type: none;
				margin-bottom: 0.6em;
				padding: 0;
			}

			#status li {
				line-height: 1.3;
			}

			#status h1 {
				text-transform: uppercase;
				font-size: 1.1em;
				margin: 0 0 0.3em;
			}

			#page-body {
				margin: 2em 1em 1.25em 18em;
			}

			h2 {
				margin-top: 1em;
				margin-bottom: 0.3em;
				font-size: 1em;
			}

			p {
				line-height: 1.5;
				margin: 0.25em 0;
			}

			#controller-list ul {
				list-style-position: inside;
			}

			#controller-list li {
				line-height: 1.3;
				list-style-position: inside;
				margin: 0.25em 0;
			}

			@media screen and (max-width: 480px) {
				#status {
					display: none;
				}

				#page-body {
					margin: 0 1em 1em;
				}

				#page-body h1 {
					margin-top: 0;
				}
			}
		</style>
	</head>
	<body>
			Index
			<br>
			Add
			<br>
			Save
			<br>
			Edit
			<br>
			Update
			<br>
			Delete
	</body>
</html>